version: '3'

services:
  db:
    image: mysql:8.0.26 
    cap_add: 
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: devise_auth_development
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      MYSQL_HOST: db
      TZ: Asia/Tokyo
    depends_on:
      - db
